export { default as Example } from './Example'
export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as Rules } from './Rules'
